(function(g){var window=this;'use strict';var U3=function(a){a.oa("cardstatechange",a.Fk()&&a.Qo()?1:0)},V3=function(a,b){var c=g.gb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Rib=function(a){var b=g.Vr(a);
a=g.Yr(a);return new g.Kr(b.x,b.y,a.width,a.height)},Sib=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.FC(a,b,function(){g.GC(e);c.apply(a,arguments)},d)},Y3=function(a){a=g.nb(a);
delete W3[a];g.xd(W3)&&X3&&X3.stop()},Uib=function(){X3||(X3=new g.uu(function(){Tib()},20));
var a=X3;a.isActive()||a.start()},Tib=function(){var a=g.sb();
g.kd(W3,function(b){Vib(b,a)});
g.xd(W3)||Uib()},Z3=function(a,b,c,d){g.Ou.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Vib=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Wib(a,a.progress);1==a.progress?(a.j=0,Y3(a),a.onFinish(),a.ir()):a.isPlaying()&&a.TK()},Wib=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Xib=function(a,b){g.Gb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$3=function(a,b,c,d,e){Z3.call(this,b,c,d,e);
this.element=a},Yib=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$3.call(this,a,b,c,d,e)},Zib=function(a){return Math.pow(a,3)},$ib=function(a){return 3*a*a-2*a*a*a},ajb=function(a){g.J.call(this);
this.B=a||window;this.j=[]},a4=function(a){return a.baseUrl||null},b4=function(a,b){return g.Ss(g.$p(a,b),function(c){return!!c})},bjb=function(a,b,c){function d(oa){var pa=oa.hovercardButton;
if(!pa)return null;pa=pa.subscribeButtonRenderer;if(!pa)return null;var ra=f(pa.unsubscribedButtonText),ba=f(pa.subscribedButtonText);if(pa.subscribed){var ya=f(pa.subscriberCountWithUnsubscribeText);var ca=f(pa.subscriberCountText)}else ya=f(pa.subscriberCountText),ca=f(pa.subscriberCountWithSubscribeText);var Pa=null;if(oa.signinEndpoint){Pa=V3(oa,"signinEndpoint","webNavigationEndpointData","url");if(!Pa){var y,V;Pa=null==(V=g.U(null==(y=pa.signInEndpoint)?void 0:y.commandMetadata,g.L2))?void 0:
V.url}if(!Pa)return null}return ra&&(ba||Pa)?{subscribed:pa.subscribed,subscribeText:ra,subscribeCount:ya,unsubscribeText:ba,unsubscribeCount:ca,enabled:pa.enabled,signinUrl:Pa,classic:oa.useClassicSubscribeButton}:null}
function e(oa){if(oa){var pa=[],ra=oa.videoId;ra&&pa.push("v="+ra);(ra=oa.playlistId)&&pa.push("list="+ra);(oa=oa.startTimeSeconds)&&pa.push("t="+oa);return"/watch?"+pa.join("&")}}
function f(oa){if(!oa)return null;var pa=oa.simpleText;return pa?pa:oa.runs?g.$p(oa.runs,function(ra){return ra.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,z=!1,D=null,G=null,F=null,H=null,O=null,Q=null;if("VIDEO"===h)g.U(l,g.rG)?m=g.U(l,g.rG).url:(Q=g.U(l,g.mT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.U(l,g.rG)?m=g.U(l,g.rG).url:(Q=g.U(l,g.mT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(z=V3(l,"browseEndpoint","browseId"))u=z,m="/channel/"+u;n=!1;q="new";(z=!!b.isSubscribe)?D=d(b):G=f(b.subscribersText)}else"WEBSITE"===h?((F=V3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(O=f(b.additionalFeesText)),(n=V3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V3(b,"title","accessibility","accessibilityData","label");var S=b.endpoint?b.endpoint.clickTrackingParams:null,
la="";if(b.metadata){var fa=f(b.metadata);fa&&(la=fa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:la,callToAction:f(b.callToAction),qV:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,GD:p,playlistLength:t,channelId:u,subscribeButton:D,subscribersText:G,isSubscribe:z,targetUrl:m||null,q6:n,sessionData:S?{itct:S}:null,uaa:q,iC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:b4(b.impressionUrls||[],a4),d6:b4(b.hovercardShowUrls||[],a4),clickUrls:b4(l.loggingUrls||[],a4),visualElement:g.xF(b.trackingParams),productPrice:H,additionalFeesText:O,watchEndpoint:Q||null}},cjb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:b4(a.impressionUrls||[],a4),elements:b4(a.elements||[],function(d,e){return bjb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.xF(a.trackingParams));return c},djb=function(a){g.uV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.dS(a)||g.fS(a);this.events=new g.MK(this);g.L(this,this.events);this.events.T(this.player,g.cK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.dK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Lb);this.events.T(window,"focus",this.Q9);this.load();var b=g.tf("STYLE");(g.Ye("HEAD")[0]||document.body).appendChild(b);g.Db(this,function(){g.Bf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},ejb=function(a){return a.player.getVideoData().Pd?"current":a.Z?"new":"current"},c4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},fjb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=cjb(f,ejb(a))));d4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Vx;d&&(c.postParams={ad_tracking:d});if(b=g.MRa(b))if(b=g.Cn(b),b=g.ne(b))a.C=g.XB(b,c)},d4=function(a,b,c){c=void 0===c?!0:c;
a.player.hf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&gjb(a);c=[];d=new g.bK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.nU(a.player,a.B.element,4),a.D=new g.EG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=hjb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.nU(a.player,f.element,4);var h=new g.bK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);ijb(a,f,e)}else g.DF(new g.WC("buildEndscreenElement null",
e))}a.player.uf(c);a.Lb()}},gjb=function(a){var b=g.yF(),c=g.zF();
c&&b&&a.endscreen.visualElement&&g.EB(g.JF)(void 0,c,b,a.endscreen.visualElement)},hjb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.iC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Tu(b.title||"")},xa:b.title},{I:"div",S:b.GD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.iC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Tu(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.iC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Tu(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)}]};c=new g.W(c);var d=g.Ze(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Cu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.gW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.iC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.Tu(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-expanding-icon",W:jjb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.iC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.Tu(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:f4(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Cu(c.element,"ytp-ce-placeholder");return c},e4=function(a){if(a.qV)var b=a.qV.thumbnails;
return jjb(b?b[b.length-1].url:null)},jjb=function(a){return a?{style:"background-image: url("+a+")"}:{}},ijb=function(a,b,c){function d(m){m&&(b.Sa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Cu(b.element,"ytp-ce-force-expand"),g4(a,c.id,!0)):(g.Eu(b.element,"ytp-ce-force-expand"),g.Eu(b.element,"ytp-ce-element-hover"),g4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Sa("mouseenter",function(){kjb(a,b,c)});
b.Sa("mouseleave",function(){ljb(a,b,c)});
a.player.U().B||b.Sa("click",function(){g.Cu(b.element,"ytp-ce-element-hover")});
b.Sa("click",function(m){mjb(a,c,m)});
b.Sa("keypress",function(m){mjb(a,c,m)});
b.Sa("focus",function(){kjb(a,b,c)});
b.Sa("blur",function(){ljb(a,b,c)});
b.Sa("touchstart",function(){kjb(a,b,c)});
var l=g.cf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Eu(b.element,"ytp-ce-element-hover");g.Eu(b.element,"ytp-ce-force-expand")});
b.Sa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.cf("ytp-sb-subscribe",b.element));d(g.cf("ytp-sb-unsubscribe",b.element));b.Sa("focus",f);b.Sa("blur",h)},mjb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Bu(d,"ytp-ce-element");){g.Bu(d,"subscribe-label")&&njb(a,b);
if(g.Bu(d,"ytp-ce-channel-subscribe"))return;d=g.Cf(d)}if(!d||g.Bu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])ljb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.uaa)njb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Cn(f4(a,b.targetUrl)),g.dH(g.ne(c),void 0,b.sessionData);else{var e=g.pS(a.player.U())||a.player.getVideoData().Pd,f=function(){var h=f4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.KB(h);e&&n&&(n.v||
n.list)?a.player.uo(n.v,l,n.list,!1,void 0,m||void 0):g.rwa(h,l)};
njb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},f4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.wS(a)+b}else return"";return b},kjb=function(a,b,c){g.Bu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Cu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.uu(function(){g.Cu(b.element,"ytp-ce-element-hover")},200)).start():g.Cu(b.element,"ytp-ce-element-hover"),h4(a,c.d6),g4(a,c.id,!0))},ljb=function(a,b,c){g.Eu(b.element,"ytp-ce-element-hover");
g.Eu(b.element,"ytp-ce-force-expand");g4(a,c.id,!1)},g4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Gu(a.j[e].element,"ytp-ce-element-shadow-show",c)},h4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||c4(a))c&&c();else{b=ojb(a,b);var e=0,f=!1,h=new g.uu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.qE(b[a],d)}},njb=function(a,b,c){h4(a,b.clickUrls,c);
(a=g.zF())&&b.q6&&g.QF(a,b.visualElement)},ojb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(pjb(b[d],c));return a},pjb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},qjb=function(a){return"string"===typeof a?a:""},i4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},rjb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},j4=function(a){return a.value?a.value:null},k4=function(a){if(!a)return null;
var b=g.Cn(qjb(a.value));b=g.ne(b);if(!b)return null;var c=i4(a.target,sjb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new rjb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},tjb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},wjb=function(a){if(!a)return null;
var b=i4(a.type,ujb),c=i4(a.trigger,vjb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=k4(a?a:null);return b?new tjb(b,c,a):null},xjb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},yjb=function(a,b){return g.Nb(a.action,b)},zjb=function(a,b){this.context=a;
this.j=b},Ajb=function(a){return a.customMessage?l4("div","iv-card-message",a.customMessage):""},m4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},Bjb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(l4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},l4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Tu(c);return{I:a,W:b,xa:c}},Cjb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.sC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.sC+");");c.dir=g.Tu(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},n4=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.aj.click,5)}},Djb=function(a,b){this.merchant=a;
this.price=b},Ejb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Fjb=function(a,b){return b?b:Ejb(a)?"current":"new"},o4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.Za=new Map;this.fb=new Map;this.context.J.addEventListener(g.cK("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.dK("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},p4=function(a,b,c,d,e,f,h){a.context.j.Sa(b,"click",function(l){a.UK(c,d,e,f||[],h||0,l)});
a.context.j.Sa(b,"touchstart",function(){a.wb=!1});
a.context.j.Sa(b,"touchmove",function(){a.wb=!0})},Gjb=function(a){var b;
return(null==(b=g.U(a,g.rG))?0:b.url)?g.U(a,g.rG).url:(a=g.U(a,g.mT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},q4=function(a,b,c){return{OW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
d_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
tK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Hjb=function(a,b,c){o4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Na=this.Ib=this.C=this.isInitialized=!1;this.cards=[];this.yb=this.Z=this.La=this.G=this.Va=this.j=null;this.ma=[];this.qa=this.N=this.og=this.Da=null;this.K=0;this.Ga=new g.uu(function(){},c.X.Ji?4E3:3E3);
g.L(this,this.Ga);this.jb=new g.uu(function(){});
g.L(this,this.jb);this.Aa=new zjb(c,function(e,f,h,l,m,n){p4(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.L(this,this.Y);this.D=this.Y.element;this.ib=new g.EG(this.Y,330);g.L(this,this.ib);this.Mb=g.cf("iv-drawer-header-text",this.D);this.B=g.cf("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ib&&r4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ib=d.C)&&s4(d)});
this.Ta=new g.MK(this);g.L(this,this.Ta);this.J.addEventListener("videodatachange",this.jt.bind(this))},Ijb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){r4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){s4(a)});
var c=b.headerText;g.Ff(a.Mb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.xF(b.trackingParams);a.N=g.xF(b.closeTrackingParams);a.og=g.xF(b.iconTrackingParams)},Jjb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.fG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,aj:{},Ro:null,zl:e.trackingParams?g.xF(e.trackingParams):null,og:f&&f.trackingParams?g.xF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
sC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};t4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.fG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:u4(a,c,b,f),sponsored:!1,aj:q4(f,e,f.command),Ro:f.trackingParams?g.xF(f.trackingParams):null,zl:e.trackingParams?g.xF(e.trackingParams):null,og:l&&l.trackingParams?g.xF(l.trackingParams):null,imageUrl:v4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.fG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,sC:null,title:f.title?g.fG(f.title):"",customMessage:f.callToAction?g.fG(f.callToAction):"",url:g.U(f.command,g.rG).url?k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(f.command,g.rG).url}):null,onClickCommand:null};t4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.fG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,aj:q4(e,f,e.endpoint),Ro:e.trackingParams?g.xF(e.trackingParams):null,zl:f.trackingParams?g.xF(f.trackingParams):null,og:l&&l.trackingParams?g.xF(l.trackingParams):null,channelId:g.U(e.endpoint,g.LU).browseId,customMessage:e.customText?g.fG(e.customText):null,bZ:v4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.fG(e.channelName):"",metaInfo:[e.subscriberCountText?g.fG(e.subscriberCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.U(e.endpoint,g.LU).canonicalBaseUrl?g.U(e.endpoint,g.LU).canonicalBaseUrl:"/channel/"+g.U(e.endpoint,g.LU).browseId}),onClickCommand:null};t4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.fG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,aj:q4(e,f,e.action),Ro:e.trackingParams?g.xF(e.trackingParams):null,zl:f.trackingParams?g.xF(f.trackingParams):null,og:l&&l.trackingParams?g.xF(l.trackingParams):null,HF:v4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.fG(e.customMessage):null,playlistVideoCount:g.fG(e.playlistVideoCount),title:e.playlistTitle?g.fG(e.playlistTitle):"",metaInfo:[e.channelName?g.fG(e.channelName):
"",e.videoCountText?g.fG(e.videoCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Gjb(e.action)}),onClickCommand:null};t4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.fG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,aj:q4(e,f,e.action),Ro:e.trackingParams?g.xF(e.trackingParams):null,zl:f.trackingParams?g.xF(f.trackingParams):null,og:l&&l.trackingParams?g.xF(l.trackingParams):null,HF:v4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.fG(e.lengthString):null,customMessage:e.customMessage?g.fG(e.customMessage):null,title:e.videoTitle?g.fG(e.videoTitle):"",metaInfo:[e.channelName?g.fG(e.channelName):
"",e.viewCountText?g.fG(e.viewCountText):""],isLiveNow:!!e.badge,url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Gjb(e.action)}),onClickCommand:null};t4(a,b)}}}}}a.K++},v4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},u4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Ljb=function(a,b){if(b=Kjb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.gg.id),g.Bf(b.qM),g.Tb(a.cards,b),a.EG(),w4(a)},r4=function(a,b,c){if(!a.C){a.ib.show();
a.Va=new g.uu(function(){g.Cu(a.context.J.getRootNode(),g.YY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ta.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.zF();d&&a.Da&&a.N&&g.OF(d,[a.Da,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.yX||(f.yX=!0,Mjb(a.context.logger,f.gg.aj.OW,b)),d&&g.OF(d,[f.gg.Ro]);U3(a.J);c&&(a.G=new g.uu(function(){a.La=a.Z;a.yb.focus()},330),a.G.start())}},s4=function(a){a.C&&(a.ib.hide(),g.LC(a.Ta),g.Eu(a.context.J.getRootNode(),g.YY.IV_DRAWER_OPEN),a.C=!1,U3(a.J),a.G&&a.G.stop(),a.G=new g.uu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Ojb=function(a){g.Du(a.Db(),
[g.YY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.nU(a.J,a.D,5);Njb(a);a.Z=g.cf("ytp-cards-button",a.J.getRootNode());a.yb=g.cf("iv-drawer-close-button",a.D);a.isInitialized=!0},Njb=function(a){var b=g.cf("iv-drawer-close-button",a.D);
a.context.j.Sa(b,"click",a.i4,a);a.context.j.Sa(a.B,"touchend",function(){a.Ga.start()});
a.context.j.Sa(a.B,"scroll",a.C4,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Bu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.EE("iv-button-shown",a.D6,a));a.ma.push(g.EE("iv-button-hidden",a.C6,a));a.ma.push(g.EE("iv-teaser-shown",a.M0,a));a.ma.push(g.EE("iv-teaser-hidden",a.E6,a));a.ma.push(g.EE("iv-teaser-clicked",a.L0,a))},Pjb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.U(b.onClickCommand,g.nfb))?void 0:c.targetId)?(a.qa=b,!0):!1},Qjb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.lQa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.U(h[0],g.KYa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},t4=function(a,b){if(!Pjb(a,b)||Qjb(a,b)){var c=Rjb(a,b);
if(c){var d={gg:b,qM:c.element,yX:!1};if(!b.onClickCommand){a.isInitialized||Ojb(a);Ljb(a,b.id);var e=Sjb(a,d);g.bc(a.cards,e,0,d);c.Ea(a.B,e);a.EG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,w4(a),Tjb(a,d),r4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Ujb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Ujb(a,d)}),w4(a))}}},Rjb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Cjb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?j4(b.url)||"":""},V:[m4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[l4("h2",void 0,b.title),d]}]}]};c=new g.W(c);n4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:j4(b.url)||"","data-ytid":b.channelId},V:[m4(b.bZ),{I:"div",
S:"iv-card-content",V:[Ajb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Bjb(b)]}]}]};c=new g.W(c);n4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:j4(b.url)||""},V:[m4(b.HF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Ajb(b),l4("h2","iv-card-primary-link",b.title),Bjb(b)]}]}]};c=new g.W(c);
n4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Cjb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?j4(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[l4("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.tf("span");g.Ff(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.le(d,"adInfo");n4(a,g.$e("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:(null==(c=b.url)?void 0:j4(c))||""},V:[m4(b.HF,d),{I:"div",S:"iv-card-content",V:[Ajb(b),l4("h2","iv-card-primary-link",b.title),Bjb(b),f]}]}]};c=new g.W(e);n4(a,g.$e("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Sjb=function(a,b){if(0===a.cards.length)return 0;
a=g.Ob(a.cards,function(c){return b.gg.startMs>c.gg.startMs||b.gg.startMs===c.gg.startMs&&b.gg.timestamp>=c.gg.timestamp?!0:!1});
return-1===a?0:a+1},Vjb=function(a){if(a.j)return"productListing"===a.j.gg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.aq(a.cards,function(c){return"productListing"===c.gg.type})}return g.aq(a.cards,function(c){return"productListing"===c.gg.type})},w4=function(a){g.Gu(a.J.getRootNode(),"ytp-cards-shopping-active",Vjb(a))},Ujb=function(a,b){if(!g.Bu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.zF(),d=a.j?a.j.gg.og:a.og;
c&&d&&g.PF(c,[d]);a.j=b;w4(a)}(c=a.isInitialized&&"none"==a.Db().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.gg.teaserDurationMs&&a.J.XA(!0,{teaserText:b.gg.teaserText,durationMs:b.gg.teaserDurationMs,onClickCommand:b.gg.onClickCommand});a.jb.isActive()||((!a.C||!a.Ga.isActive()&&a.Na)&&Tjb(a,b),a.jb.start(910+b.gg.teaserDurationMs))}},Tjb=function(a,b){a.Y.Gb?(b=new Z3([0,
a.B.scrollTop],[0,b.qM.offsetTop],600,$ib),a.context.C.Sa(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Sa(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.bG(a.Y,!0),a.B.scrollTop=b.qM.offsetTop,g.bG(a.Y,!1))},x4=function(a){return a.j&&a.j.gg?a.j.gg:a.cards[0]&&a.cards[0].gg?a.cards[0].gg:null},Kjb=function(a,b){return g.Nb(a.cards,function(c){return c.gg.id===b})},y4=function(a,b,c){o4.call(this,a,b);
this.annotation=c;this.isActive=!1},Wjb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z4=function(a,b,c){y4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Xjb=function(a,b){var c=void 0===c?0:c;
var d=Rib(b).width;g.Tr(b,d);c=new Yib(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Zib);g.L(a,c);a.context.C.Sa(c,"begin",function(){g.Zr(b,!0)});
c.play()},$jb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.gW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Ea(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Zr(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Nr(l,"right",b.image_width+"px");g.yf(a.Db(),l);a.C=new g.uu(function(){Yjb(a,h,l)},500);
g.L(a,a.C);a.context.j.Sa(a.Db(),"mouseover",function(){Zjb(a,h,l,f,b.image_height)});
a.context.j.Sa(a.Db(),"mouseout",function(){a.C.start()})}},Zjb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Yr(b);a.j||(b.style.width=g.Sr(f.width,!0),c.style.width=g.Sr(f.width,!0));g.Nr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Nr(d,"right","1px");a.D=!0;g.Zr(b,!0);a.G=new g.uu(function(){g.Cu(this.Db(),"iv-branding-active")},0,a);
a.G.start()}},Yjb=function(a,b,c){g.Eu(a.Db(),"iv-branding-active");
a.K=new g.uu(function(){g.Zr(b,!1);a.j||(c.style.width=g.Sr(0,!0))},250);
a.K.start();a.D=!1},akb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},bkb=function(a,b,c){y4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.uu(function(){d.j.setAttribute("aria-hidden","true");g.Zr(d.C,!1);g.Zr(d.B,!0)},700,this);
g.L(this,this.G)},ekb=function(a,b,c){c.stopPropagation();
ckb(a);dkb(a,b);a.j.focus()},fkb=function(a){a.isCollapsed||a.Z||a.D||(g.Cu(a.Db(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},ckb=function(a){a.G.stop();
a.isCollapsed&&(g.Fu(a.Db(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Zr(a.B,!1),g.Zr(a.C,!0))},dkb=function(a,b){a.D||(a.D=g.rg(function(){gkb(this);
fkb(this)},b,a))},gkb=function(a){a.D&&(g.Xa.clearTimeout(a.D),a.D=null)},hkb=function(a){this.J=a},Mjb=function(a,b,c){b&&(c?A4(a,b.map(function(d){return g.iu(d,c)})):A4(a,b))},A4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.qE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},ikb=function(a){g.uV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new hkb(this.player);this.D=new g.MK(this);this.G=this.ox=null;this.events=new g.MK(this);this.rh=this.Z=this.j=null;this.ma=[];g.L(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.N0,this);this.subscribe("resize",this.jJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.GY,this);g.L(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.nU(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ma:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.C.element.appendChild(a);this.Yt()&&this.load();var c=this.createElement({I:"style"});(g.Ye("HEAD")[0]||document.body).appendChild(c);g.Db(this,function(){g.Bf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},jkb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.Zr(a,!1);return a},kkb=function(a,b){b=!b.isCued()&&!g.KG(b,1024);
g.bG(a.B,b);g.bG(a.C,b)},lkb=function(a,b,c){a.N=!0;
a.G=g.XB(b,c)},mkb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.kb(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(mkb(a,e))}return c},qkb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.RB(h)&&h.responseXML?h.responseXML:null)&&nkb(a,h)}};
g.dD()&&(d.onFinish=okb(a,d.onFinish));d.postParams={ic_only:"1"};pkb(d,c);a.N=!0;g.XB(b.Ta,d)}}},pkb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.JG&&(a.postParams.ic_coll=b.JG);b.rM&&(a.postParams.ic_xml=b.rM);b.yK&&(a.postParams.ic_track=b.yK)},rkb=function(a){var b=new g.W({I:"div"});
g.Zr(b.element,!1);var c=new Hjb(a.player,b.element,B4(a));g.L(c,b);b.Ea(a.B.element);c.vF();return c},tkb=function(a,b){var c,d;
if(b=null==(c=b.Hd)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,skb(a,b),b.headerText&&a.rh&&(c=g.fG(b.headerText),a.rh.setAttribute("title",c))},B4=function(a){if(!a.Z){var b=new ajb(a);
g.L(a,b);var c=new g.so(a);g.L(a,c);a.Z=new akb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.jj)}return a.Z},nkb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.zF();if(e){var f=g.yF();f&&g.EB(g.Cua)(void 0,e,f,[g.xF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=mkb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=i4(f.type,ukb),p=i4(f.style,vkb),q=qjb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=wjb;if(null==t)var u=null;else if(g.gb(t)){l=[];for(var z=g.v(t),D=z.next();!D.done;D=z.next()){var G=f(D.value);
G&&l.push(G)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new xjb(m,n,p,u,r):null}else e=null}catch(fa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=jkb(f),O=null;switch(l.type){case "branding":if(f.player.U().Ud)break;f.B.element.appendChild(H);O=new z4(H,B4(f),l);break;case "promotion":g.nU(f.player,H,4),O=new bkb(H,B4(f),l)}O&&O.vF();if(f=O)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=rkb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var Q=e&&e.data&&e.data.card_type;
f=e.data;if(Q)switch(l=f.tracking||{},l={OW:l.impression,click:l.click,close:l.close,d_:l.teaser_impression,tK:l.teaser_click},H=f.tracking_params||{},O=null,Q){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,aj:l,Ro:H.card?g.xF(H.card):null,zl:H.teaser?g.xF(H.teaser):null,og:H.icon?g.xF(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,bZ:f.image_url,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,aj:l,Ro:H.card?g.xF(H.card):null,zl:H.teaser?
g.xF(H.teaser):null,og:H.icon?g.xF(H.icon):null,HF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "productListing":f.signin_url&&(O=k4({target:"current",value:f.signin_url}));Q=[];for(var S=f.offers||[],la=0;la<S.length;la++)Q.push(new Djb(g.Le(S[la].merchant),g.Le(S[la].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,aj:l,Ro:H.card?g.xF(H.card):null,zl:H.teaser?g.xF(H.teaser):null,og:H.icon?g.xF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,sC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Chb:O,Bhb:f.signin_title?f.signin_title:void 0,Ahb:f.signin_message?f.signin_message:void 0,offers:Q,onClickCommand:null};t4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,aj:l,Ro:H.card?g.xF(H.card):
null,zl:H.teaser?g.xF(H.teaser):null,og:H.icon?g.xF(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,sC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,aj:l,Ro:H.card?g.xF(H.card):null,zl:H.teaser?g.xF(H.teaser):null,og:H.icon?g.xF(H.icon):null,HF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},t4(c,e)}}else Ijb(a.j,e);c=!0}}c&&
(U3(a.player),a.jJ())},skb=function(a,b){var c=!1;
a.j||(a.j=rkb(a),g.L(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Jjb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.HT(f)||(c=a.j,d=b.headerText?g.fG(b.headerText):"",g.Ff(c.Mb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.xF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.xF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.og=b.icon.infoCardIconRenderer.trackingParams?g.xF(b.icon.infoCardIconRenderer.trackingParams):null,a.jJ());U3(a.player)}},wkb=function(a,b,c,d,e){if(!a.player.U().Ud){var f=[];
b.navigationEndpoint&&g.U(b.navigationEndpoint,g.LU)&&g.U(b.navigationEndpoint,g.LU).browseId&&f.push(new tjb("openUrl","click",new rjb("/channel/"+g.U(b.navigationEndpoint,g.LU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.U(b.subscribeButton,
g.AT)){d.channel_id=g.U(b.subscribeButton,g.AT).channelId;var l;b=g.U(b.subscribeButton,g.AT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.fG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.fG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.fG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.fG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.U(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.L2))?void 0:m.url)||"";l={subscribeText:g.fG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.fG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new xjb(c,"branding","branding",f,d);l=jkb(a);a.B.element.appendChild(l);f=new z4(l,B4(a),f);f.vF();g.L(f,f);a.K[c]=f}},okb=function(a,b){return function(){var c=g.La.apply(0,arguments);
a.isDisposed()||a.ma.push(g.lu.Ki(function(){b.apply(null,g.sa(c))}))}},xkb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.fU.prototype.XA=g.ha(19,function(a,b){var c=g.LV(this.Eb());c&&c.XA(a,b)});
var W3={},X3=null;g.tb(Z3,g.Ou);g.k=Z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Y3(this);this.startTime=a=g.sb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.aJ();this.Xl("play");this.isPaused()&&this.Xl("resume");this.j=1;var b=g.nb(this);b in W3||(W3[b]=this);Uib();Vib(this,a);return!0};
g.k.stop=function(a){Y3(this);this.j=0;a&&(this.progress=1);Wib(this,this.progress);this.Xl("stop");this.ir()};
g.k.pause=function(){this.isPlaying()&&(Y3(this),this.j=-1,this.Xl("pause"))};
g.k.ya=function(){0==this.j||this.stop(!1);this.Xl("destroy");Z3.Of.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.TK=function(){this.Xl("animate")};
g.k.Xl=function(a){this.dispatchEvent(new Xib(a,this))};
g.tb(Xib,g.Gb);g.tb($3,Z3);$3.prototype.C=function(){};
$3.prototype.TK=function(){this.C();$3.Of.TK.call(this)};
$3.prototype.ir=function(){this.C();$3.Of.ir.call(this)};
$3.prototype.aJ=function(){this.C();$3.Of.aJ.call(this)};
g.tb(Yib,$3);Yib.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(ajb,g.J);g.k=ajb.prototype;g.k.Sa=function(a,b,c,d){c=(0,g.qb)(c,d||this.B);a=g.FC(a,b,c);this.j.push(a);return a};
g.k.yI=function(a,b,c,d){c=(0,g.qb)(c,d||this.B);a=Sib(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.GC(a);g.Tb(this.j,a)};
g.k.Lf=function(){g.GC(this.j);this.j.length=0};
g.k.ya=function(){this.Lf();g.J.prototype.ya.call(this)};g.x(djb,g.uV);g.k=djb.prototype;g.k.load=function(){g.uV.prototype.load.call(this);if(!c4(this)){var a=g.NRa(this.player.getVideoData());a?(a=cjb(a,ejb(this)),d4(this,a,!1)):fjb(this)}};
g.k.unload=function(){d4(this,null);this.C&&(this.C.abort(),this.C=null);g.uV.prototype.unload.call(this)};
g.k.Hh=function(a,b){return c4(this)?"loadCustomEndscreenRenderer"===a?(a=cjb(b,"new"),d4(this,a),!0):null:null};
g.k.getOptions=function(){return c4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Lb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ykb.length;f++){var h=Math.abs(b.width-ykb[f]);if(-1===e||d>=h)e=f,d=h}d=zkb[e];this.B&&g.Nr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Xr(e.element,m,f);g.Tr(e.element,n,p);g.Fu(e.element,Akb);256<m||256<f?g.Cu(e.element,"ytp-ce-large-round"):96<m||96<f?g.Cu(e.element,"ytp-ce-medium-round"):g.Cu(e.element,"ytp-ce-small-round");g.Fu(e.element,Bkb);m=h.left+h.width/2;h=h.top+l/2;g.Cu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Fu(e.element,zkb);g.Cu(e.element,d);(e=g.Ze(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Nr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())h4(this,this.endscreen.impressionUrls),(a=g.zF())&&this.endscreen.visualElement&&g.NF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Cu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Cu(b,"ytp-ce-shown");h4(this,c.impressionUrls);(b=g.zF())&&g.NF(b,c.visualElement);this.player.U().K&&this.player.Ra("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Eu(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Eu(b,"ytp-ce-shown");this.player.U().K&&this.player.Ra("endscreenelementhidden",a)}};
g.k.Q9=function(a){var b=this;a.target===window&&(new g.uu(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Fu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ykb=[346,426,470,506,570,640,853,1280,1920],zkb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Bkb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Akb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var sjb={Sqa:"current",OQa:"new"};var ujb={CLOSE:"close",pUa:"openUrl",SUBSCRIBE:"subscribe"},vjb={opa:"click",CLOSE:"close",pCa:"hidden",vZa:"rollOut",wZa:"rollOver",e0a:"shown"};xjb.prototype.bf=function(){var a=yjb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var vkb={dka:"anchored",l0:"branding",CHANNEL:"channel",Iqa:"cta",sCa:"highlightText",tGa:"label",PLAYLIST:"playlist",NWa:"popup",b3a:"speech",SUBSCRIBE:"subscribe",s6a:"title",VIDEO:"video",Ecb:"website"},ukb={l0:"branding",gna:"card",Vsa:"drawer",rCa:"highlight",vMa:"marker",qYa:"promotion",TEXT:"text",jeb:"widget"};g.x(o4,g.J);g.k=o4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.bK(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.fb.set(a,e);this.context.J.uf([a])};
g.k.vF=function(){this.context.B.subscribe("resize",this.EG,this)};
g.k.Db=function(){return this.element};
g.k.UK=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Bf(this.Db())};
g.k.EG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=j4(a);if(f){var h=Fjb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Pd||!1,n=g.KB(f||"");m&&n&&(n.v||n.list)?e.context.J.uo(n.v,b,n.list,!1):g.dH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);A4(this.context.logger,c,l,d);Ejb(f)||(c=g.zF(),d=b.itct,c&&d&&g.QF(c,g.xF(d)))}};
g.k.ya=function(){this.Za.clear();this.fb.clear();g.J.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.L(this,a);return a.element};g.x(Hjb,o4);g.k=Hjb.prototype;g.k.jt=function(){this.qa&&t4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Yr(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.EG=function(){var a=this.isAvailable();g.Zr(this.Db(),a);g.Gu(this.context.J.getRootNode(),g.YY.IV_DRAWER_ENABLED,a);U3(this.J)};
g.k.destroy=function(){this.J.XA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.FE(this.ma);g.LC(this.Ta);this.Va&&this.Va.dispose();this.G&&this.G.dispose();o4.prototype.destroy.call(this)};
g.k.i4=function(){if(this.C){A4(this.context.logger,x4(this).aj.close);var a=g.zF();a&&this.N&&g.QF(a,this.N);s4(this)}};
g.k.C4=function(){g.Gu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.D6=function(){var a=g.zF(),b=x4(this);b=b?b.og:this.og;a&&b&&g.OF(a,[b])};
g.k.C6=function(){var a=g.zF(),b=x4(this);b=b?b.og:this.og;a&&b&&g.PF(a,[b])};
g.k.M0=function(){var a=x4(this);A4(this.context.logger,a.aj.d_);var b=g.zF();b&&a&&g.OF(b,[a.zl,a.og])};
g.k.E6=function(){var a=g.zF(),b=x4(this);a&&b&&g.PF(a,[b.zl])};
g.k.L0=function(a){var b=x4(this),c=g.zF();this.j?a?(a=this.context.logger,A4(a,b.aj.tK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.zl&&g.QF(c,b.zl)):(a=this.context.logger,A4(a,b.aj.tK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.og&&g.QF(c,b.og)):(a=this.context.logger,A4(a,b.aj.tK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.og&&g.QF(c,this.og))};g.x(y4,o4);y4.prototype.vF=function(){o4.prototype.vF.call(this);Wjb(this)};
y4.prototype.show=function(){o4.prototype.show.call(this);var a=g.zF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.OF(a,[g.xF(b.itct)])};
y4.prototype.hide=function(){o4.prototype.hide.call(this);var a=g.zF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.PF(a,[g.xF(b.itct)])};g.x(z4,y4);z4.prototype.Qw=function(){g.Cu(this.Db(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Zr(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Db().appendChild(b);var c=this.annotation.bf();c&&p4(this,b,c,this.annotation.id,a.session_data);$jb(this,a)};
z4.prototype.show=function(){if(!this.isActive&&(y4.prototype.show.call(this),this.N||(this.Qw(),this.N=!0),g.Zr(this.Db(),!0),this.isActive=!0,this.B)){try{Xjb(this,this.B)}catch(a){}g.Cu(this.context.J.getRootNode(),"ytp-branding-shown")}};
z4.prototype.hide=function(){this.isActive&&(y4.prototype.hide.call(this),g.Zr(this.Db(),!1),this.isActive=!1,g.Eu(this.context.J.getRootNode(),"ytp-branding-shown"))};
z4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);y4.prototype.destroy.call(this)};g.x(bkb,y4);g.k=bkb.prototype;
g.k.Qw=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Db().setAttribute("aria-hidden","true");this.Db().setAttribute("aria-label","Promotion");this.Db().tabIndex=0;var e=this.annotation.bf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&p4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Dn(f,j4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&p4(this,
this.Db(),e,this.annotation.id,b.session_data,void 0,c)}g.Cu(this.j,"iv-click-target");e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.Cu(this.j,"iv-click-target"),e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Sa(this.B,"click",function(q){ekb(a,5E3,q)});
c.appendChild(this.B);g.Zr(this.B,!1);this.context.j.Sa(this.Db(),"mouseover",this.E5,this);this.context.j.Sa(this.Db(),"mouseout",this.D5,this);this.context.j.Sa(this.Db(),"touchend",function(q){ekb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Sa(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.z5:this.y5,this);c.appendChild(this.C);g.Du(this.Db(),d);h&&(g.yf(this.Db(),h),n&&h.appendChild(n));g.yf(this.Db(),this.N);g.yf(this.Db(),c)};
g.k.show=function(){this.isActive||(y4.prototype.show.call(this),this.Y||(this.Qw(),this.Y=!0),g.Zr(this.Db(),!0),g.rg(function(){g.Eu(this.Db(),"iv-promo-inactive")},100,this),this.Db().removeAttribute("aria-hidden"),this.isActive=!0,gkb(this),ckb(this),dkb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Cu(this.Db(),"iv-promo-inactive"),this.isActive=!1,this.Db().setAttribute("aria-hidden","true"))};
g.k.UK=function(a,b,c,d,e,f){return this.isCollapsed?!1:y4.prototype.UK.call(this,a,b,c,d,e,f)};
g.k.E5=function(a){this.Z=!0;ekb(this,500,a)};
g.k.D5=function(){this.Z=!1;fkb(this)};
g.k.y5=function(a){a.stopPropagation();this.hide()};
g.k.z5=function(a){a.stopPropagation();gkb(this);this.isCollapsed=!0;g.Cu(this.Db(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();y4.prototype.destroy.call(this)};g.x(ikb,g.uV);g.k=ikb.prototype;g.k.Hh=function(a,b){if(!xkb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.q2(b))&&nkb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Ljb(this.j,b),U3(this.player)),!0}return null};
g.k.getOptions=function(){return xkb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Yt=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Pd&&a.ma||g.ZT(this.player.app)?!1:1===c&&!b.nU||a.Na.get(b.videoId)||g.IT(b)||g.ORa(b)?!0:!1};
g.k.jJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.Xr(this.C.element,a.width,a.height);g.Tr(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Pk();a=this.j;b=b.width;g.Gu(a.D,"iv-drawer-small",426>=b);g.Gu(a.D,"iv-drawer-big",1280<=b)}};
g.k.N0=function(a){kkb(this,a.state);g.KG(a.state,2)&&(this.Fk()&&this.Qo()&&2!==this.player.getPresentingPlayerType()&&this.YA(!1),this.XA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.RB(h)&&h.responseXML?h.responseXML:null)&&(nkb(b,h),g.Cu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.uV.prototype.load.call(this);kkb(this,this.player.Tb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.dD()&&(a=okb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&pkb(e,f);f=f&&(f.rM||f.JG);if(!c.Au||f)c.Ta?lkb(this,c.Ta,e):(this.ox=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.HT(h))&&!b.Y&&tkb(b,h)},this.player.addEventListener("videodatachange",this.ox));
g.nU(this.player,this.C.element,4);this.jJ();(f=g.IT(c))&&skb(this,f);(f=g.ORa(c))&&f.featuredChannel&&wkb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.rh=g.cf("ytp-cards-button",this.player.getRootNode());g.HT(c)&&tkb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&lkb(this,b.Ta,a)};
g.k.unload=function(){this.player.hf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,U3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.uV.prototype.unload.call(this);this.C.detach();this.ox&&(this.player.removeEventListener("videodatachange",this.ox),this.ox=null)};
g.k.GY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?qkb(this):this.load())};
g.k.Fk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.Qo=function(){return!!this.j&&this.j.C};
g.k.YA=function(a,b,c){b=void 0===b?!1:b;this.Fk();this.j&&(a?c?r4(this.j,c,b):r4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):s4(this.j))};
g.k.XA=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.GY,this);g.Eu(this.player.getRootNode(),g.YY.IV_DRAWER_OPEN);for(var a=this.ma,b=g.lu,c=0,d=a.length;c<d;c++)b.Kj(a[c]);this.ma.length=0;g.uV.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.L(this,a);return a.element};g.tV("annotations_module",ikb);g.tV("creatorendscreen",djb);})(_yt_player);
